[package]
name = "five_words_rs"
version = "0.1.0"
edition = "2021"
authors = ["Rainbaby"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
itertools = "0.10.5"
memmap = "0.7.0"
rand = "0.8.5"
rayon = "1.5.3"